import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 Configuration optimized for 5 module categories:
 - Module 1: ROS 2 Foundation
 - Module 2: Digital Twin Simulation
 - Module 3: AI Perception & Navigation
 - Module 4: VLA Integration
 - Module 5: Capstone Project
 */
const sidebars: SidebarsConfig = {
  // Autogenerate sidebar from docs folder structure
  // Module categories will be created using _category_.json files in each module directory
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
